.gitignore
models/User.js
package-lock.json

finished user-model

---

models/Job.js

added contact_email along with references
added user_id along with references

finished job.js with contact_email and user_id along with references

---

.gitignore
public/css/style.css
public/js/main.js
test.html

-Added navbar to main.handlebars that will appear site-wide

main.handlebar nav bar and formatting

---

models/index.js

finished creating relations in index-models

created relations between models in index-models, and exported the models

---

public/css/style.css
test.html

Added content to the About Us handlebar page and added bootstrap formatting

Added about us content and formatted page view

---

controllers/api/login-router.js

Updated login-router posts

---

controllers/api/index.js

Updated index.js in controllers/api with login, job, and hiring route

Updated index.js in controllers/api with login, job, and hiring route

---

.gitignore
test.html
views/home.handlebars

Added content to home handlebar and seeking/hiring buttons

Added hiring/seeking buttons and handlebar content for home page

---

.gitignore
controllers/api/jobs-router.js
controllers/api/login-router.js
controllers/api/users-router.js

added const to job-router api
commented on the login route codes for future reference

added const to job-router, addedx comments to login/user for login post

---

controllers/api/index.js
controllers/homeRoutes.js

added exclude attribute req.session.jobs in home routes
deleted hiring router in index router

Home routes

---

seeds/jobs.js

Jobs seeds

---

.gitignore
config/connection.js
package-lock.json
package.json

added require(dotenv).config() to connection.js

Fixed connection.js added require(dotenv).config()

---

config/session.js
controllers/api/jobs-router.js
controllers/home-router.js
seed/jobsSeed.js
views/hiring-post.handlebars
views/job-details.handlebars
views/job-seeking.handlebars

Took off with Auth
Added routes to handlebars for render
added handlebars that are missing

took out withAuth, edited handlebar routes, added handlebars

---

controllers/home-router.js

commented out the homeroute for renders
changed names for routes

commented out the homeroute to only render views, and changed names for router

---

views/hiring-detail.handlebars
views/hiring-post.handlebars
views/hiring-posts.handlebars
views/job-details.handlebars
views/job-posts.handlebars
views/job-seeking.handlebars
views/layouts/main.handlebars
views/partials/jobcard.handlebars

Added new necessary handlebars and created placeholder content for them

added handlebars files, filled out hiring-detail and job-details files

---

controllers/api/users-router.js
controllers/home-router.js
public/js/login.js
public/js/logout.js
public/js/signup.js
views/layouts/main.handlebars

linked buttons to href; added new get route

---

controllers/home-router.js

uncommented out homeroutes and fixed it so handlebars load

fixed the routes in homeroutes so it can load handlebars

---

views/hiring-posts.handlebars
views/home.handlebars

added seeking and hiring buttons links

---

public/css/style.css
public/js/main.js
views/layouts/main.handlebars

Home button returns to seeking/hiring page

added home button with functionality

---

views/partials/jobcard.handlebars

job cards now link to the relevant job detail cards

quickfix to point jobcards toward the right jobdetail id

---

views/hiring-posts.handlebars

fast fix for job posting id not matching

added id correlation to hiring posts side of job listings

---

controllers/home-router.js
package.json

- Updated code to display only job posts that are equal/not equal to hardcoded user_id; 
- changed view referenced in hiring post route to display hiring-posts instead of job-seeking

Where Clause Revision

---

controllers/home-router.js

added code to the homerouter for hiringposts/:id to feed data to handlebar.

finished feeding data from hiringposts/:id to the handlebar

---

controllers/api/users-router.js
public/js/signup.js
views/signup.handlebars

Updated routes for front end registration page to correctly post new user data when inputting and submitting

Resolved Sign-up issue

---

controllers/api/index.js
public/js/delete.js
seed/jobsSeed.js
views/partials/hiredetail.handlebars

added the delete button code back
Fixed index in routes

added delete button code and fixed index

---

controllers/api/users-router.js
public/js/login.js
views/login.handlebars

Resolved fe/be login routes

---

public/css/style.css
views/hiring-detail.handlebars
views/hiring-posts.handlebars
views/home.handlebars
views/job-details.handlebars
views/job-seeking.handlebars
views/partials/hirecard.handlebars
views/partials/hiredetail.handlebars
views/partials/jobdetail.handlebars
views/partials/seekcard.handlebars

Added swipes and changed a few formatting issues on the views

Modified transitions and revised borders on views

---

seed/userSeed.js

fixed user seeds

---

controllers/api/jobs-router.js
controllers/home-router.js
public/css/style.css
public/js/makejob.js
views/layouts/main.handlebars
views/postjob.handlebars

Started work on job post option

added job post button and route

---

controllers/api/index.js
controllers/api/jobs-router.js
controllers/api/users-router.js
controllers/index.js

commented out the login-router.js
changed the index to comment out the login-router.js
fixed jobs and user router to have get requests
commented out the if statement in jobs router for later but we still need it but we need to figure out how to make it properly

figured out why the api was not working

---

controllers/api/jobs-router.js

Why Chris, why?
if (!req.body.job_name || !req.body.description || !req.body.price || !req.body.zipcode || !req.body.contact_email)

added an ! for req.body.contact_mail, works now

---

public/css/style.css
views/login.handlebars
views/postjob.handlebars
views/signup.handlebars

CSS formatting and page prettification

login and signup formatting and centering

---

README.md

Finished all of the README except for gif demo

Finished readme except for Demo gifs

---

models/Job.js

added validation to zipcode so they have to put a 5 digit zipcode

added validation for zipcode, min-max of 5 intergers

---

public/css/style.css
views/hiring-posts.handlebars
views/home.handlebars
views/job-seeking.handlebars
views/layouts/main.handlebars
views/partials/hirecard.handlebars
views/partials/seekcard.handlebars

CSS changes for improved style

added box shadows, reformatted pages and changed column layout

---

views/postjob.handlebars

edited the margins in the forms

handlebar form fixes

---

public/js/makejob.js
views/postjob.handlebars

added validation for email, price and zipcode fields on job submit

---

controllers/api/jobs-router.js
models/Job.js
package-lock.json
package.json
public/js/makejob.js
views/partials/hirecard.handlebars
views/partials/seekcard.handlebars

added dayjs functionality and added date to job cards
